### ISSUE TITLE
Fetching delay

### ISSUE THREAD

**Issue by p2p-sergey-y** [wealdtech/chaind#20]
Hello!
Thanks for this app, it's cool!
I'm faced with an interesting case: I have teku node in archive mode with `data-storage-archive-frequency: 8192` and it can answer to some API really long time. As example:
```
:~$ time curl -s localhost:3500/eth/v1/beacon/states/1701967/committees > /dev/null

real    9m20.688s
user    0m0.019s
sys     0m0.003s

:~$ time curl -s localhost:3500/eth/v1/beacon/states/1701957/committees > /dev/null

real    10m13.902s
user    0m0.017s
sys     0m0.009s
```
The thing is that chaind updates blocks longer than new blocks appear  in that case. As result chaind starts to lag behind the head more and more.
For fast resolving this issue, I made some non-production ready [changes](https://github.com/p2p-sergey-y/chaind/blob/0f655c612efc0a2b6b647db3a1be6c7f4bf57635/services/blocks/standard/service.go#L185) : tried to use worker pool for simultaneous requests for speeding up query process just after restart the service.

How about to implement something similar to upstream? I can help with PR if it's interesting for you and you can help me with the architect approach how to implement it.

**Comment by mcdee** [comment]
I have had a think about this, and there area  few issues.

There is a concern that overloading the beacon chain node in this way will cause more harm than good, as it will cause duplication of work as the same path is trodden for each block in parallel.  In general you really should run teku in full archive mode if you want to obtain data from it; the time/space tradeoff for doing so very heavily favours giving teku more space to reduce the time taken to return blocks.

A separate concern is around the loose coupling of modules, and the impact that out-of-order fetching of blocks may have.  Although the idea of missed slots was good in theory, in practice it has resulted in confusion where a slot without data in chaind could be a missing block, or just a block that hasn't been gathered yet.  This makes additional modules such as the finalizer and summarizer much harder to manage, so the next version of chaind will do away with missed slots and instead stop at the first failure to obtain a block.  This provides a much higher level of surety that if block 100 is present in the DB then all blocks prior to that are either also present in the DB or not in the chain, which in turn makes finalizing a far less error-prone process.

Ultimately, the simplicity of keeping chaind sequential for fetching data is worth the requirement that the beacon node keeps a complete state log.  If you are still seeing issues after running teku in full archive mode then some sort of batching or grouping system may be possible, but I'd rather avoid it due to the additional complexity it would bring.

**Comment by p2p-sergey-y** [comment]
Thank you for clear explanation!
So I close this case due to architecture approach
