### ISSUE TITLE
Running without "old" data

### ISSUE THREAD

**Issue by henridf** [wealdtech/chaind#63]
I'm running a chaind instance where I don't need historical data (where "historical" would be something like "more than 30d old").

To reduce storage requirements, I was wondering about dropping that data. As far as I can tell, chaind would continue to operate fine, but I might be missing something. Are there any obvious gotchas to doing this? Thanks for any context/info, and fully understood if the answer is "might work but no guarantees and you're on your own :)"

**Comment by mcdee** [comment]
The single largest source of data by far is validators.  Validator balances and summaries update once every ~6 minutes for each validator, so that's two hundred million rows plus indices per day.

The two tables are `t_validator_balances` and `t_validator_epoch_summaries`.  You could run a periodic cleanup with something like:

```
DELETE FROM t_validator_balances WHERE f_epoch < (SELECT MAX(f_epoch)-(225*30) FROM t_validator_balances);
DELETE FROM t_validator_epoch_summaries WHERE f_epoch < (SELECT MAX(f_epoch)-(225*30) FROM t_validator_epoch_summaries);
```

which would remove any entries more than 30 days old.  You may want to follow that up with a `VACUUM (ANALYZE,FULL) t_validator_balances` and same for `t_validator_epoch_summaries` to actually free up the space and to keep the indexer up-to-date.

You could do something similar for the rest of the data, but the effort:reward ratio goes up significantly.  Your next target would be `t_blocks` (the majority of the data is in `t_attestations` but it's linked so a delete of the block will cascade delete the attestations) but unless you are seriously starved of disk space I wouldn't bother.

As to if it will work: probably.  I can't think of a particular reason why it wouldn't, and the design says that it should, but no promises.  The one situation that does leap to mind is a long period of non-finality, but as long as you don't delete data that has not been finalized and summarized it should be fine.

**Comment by henridf** [comment]
This is super helpful and confirms what I was expecting/hoping for. Thanks!
