### ISSUE TITLE
postgres tuning recommendations and specs?

### ISSUE THREAD

**Issue by henridf** [wealdtech/chaind#94]
Would you be able to provide some info about a known/working postgres config ? 

My setup is having trouble keeping up (it seems like this has started since enabling pruning, but that may be a coincidence), and not having serious pg ops experience, I'm unsure if/how the bottleneck might be there. I see that autovacuum jobs are running for days so am wondering if something needs to be tweaked there. 

I understand that this isn't a postgres support channel, but if you had to make any non-standard settings changes that would be welcome, as well as knowing what type of specs your DB has (mine is 80GB RAM/16CPUs, using about 18TB storage).

Thanks!

**Comment by mcdee** [comment]
Unfortunately each postgresql installation can be very different.  You can find a number of guides at https://wiki.postgresql.org/wiki/Performance_Optimization that may be of use, there are a lot of parameters that can be tweaked to provide better performance if you have lots of memory and/or SSDs.

Specifically for chaind, if your pruning has removed a large number of rows from the table it may well be that you need to either vacuum the relevant tables (`t_validator_balances` and/or `t_validator_epoch_summaries`), or reindex the tables' indices (or both).  If you have an autovacuum running that may be attempting to address the issue, but if the indices are no longer being used that would cause problems due to the remaining size of the table, and a lot of contention whilst the vacuum was running.

An alternative may be to drop and recreate the indices rather than attempt to reindex them, but again I'm afraid I can't say if that would prove to be a faster resolution to the issue.

**Comment by henridf** [comment]
Belated thanks a bunch for the feedback. I haven't fully solved the perf issues yet, but this was helpful. Closing as no further action is needed.
